class KyoukaBaseException(Exception):...

class PluginBaseException(KyoukaBaseException):...

class PluginTypeSupport(PluginBaseException):...
class PluginNotSupport(PluginBaseException):...


class KyoukaAPIException(KyoukaBaseException):...

class KyoukaAPIValueException(KyoukaAPIException):...
class BridgeNotFoundException(KyoukaBaseException):...


class KyoukaMSGException(KyoukaBaseException):...

class MsgContentTypeUnsupported(KyoukaMSGException):...